const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const sems=[...Array(14)].map((_,i)=>i+1); let me=null, students=[];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(name,opts={}){let r=await fetch(`index.php?api=${name}`,opts),d=await r.json();if(!r.ok||!d.ok)throw Error(d.message||'Terjadi kesalahan');return d}
function fd(form){return new URLSearchParams(new FormData(form))}
function showLogin(){ $('#loginPage').style.display='flex';$('#studentApp').classList.remove('app-visible');$('#adminApp').classList.remove('admin-visible'); }
function showStudent(){ $('#loginPage').style.display='none';$('#studentApp').classList.add('app-visible');$('#adminApp').classList.remove('admin-visible'); }
function showAdmin(){ $('#loginPage').style.display='none';$('#adminApp').classList.add('admin-visible');$('#studentApp').classList.remove('app-visible'); loadAdmin(); }
async function init(){try{let d=await api('me');if(d.user.role==='admin')showAdmin();else{me=d.student;showStudent();renderStudent();}}catch(e){showLogin()}}
$('#studentMode').onclick=()=>{$('#studentMode').classList.add('active');$('#adminMode').classList.remove('active');$('#registerToggle').style.display='block';$('#adminHint').style.display='none';$('#registerForm').style.display='none';$('#loginForm').style.display='block'};
$('#adminMode').onclick=()=>{$('#adminMode').classList.add('active');$('#studentMode').classList.remove('active');$('#registerToggle').style.display='none';$('#adminHint').style.display='block';$('#registerForm').style.display='none';$('#loginForm').style.display='block'};
$('#registerToggle').onclick=()=>{$('#loginForm').style.display='none';$('#registerForm').style.display='block';$('#registerToggle').textContent='Kembali ke login'};
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{let d=await api('login',{method:'POST',body:fd(e.target)});if(d.role==='admin')showAdmin();else{let m=await api('me');me=m.student;showStudent();renderStudent()}}catch(x){$('#loginMsg').textContent=x.message}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();try{let d=await api('register',{method:'POST',body:fd(e.target)});$('#registerMsg').textContent=d.message;e.target.reset();$('#loginForm').style.display='block';$('#registerForm').style.display='none';}catch(x){$('#registerMsg').textContent=x.message}};
async function logout(){await api('logout');location.reload()}
$('#studentLogout').onclick=logout;$('#adminLogout').onclick=logout;
$$('.menu button').forEach(b=>b.onclick=()=>{ $$('.menu button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.section').forEach(s=>s.classList.remove('active'));$('#'+b.dataset.section).classList.add('active');$('#pageTitle').textContent=b.textContent.replace(/^\S+\s/,'');if(b.dataset.section==='krs')loadKrs();if(b.dataset.section==='khs')loadKhs();if(b.dataset.section==='transkrip')loadTranskrip()});
function semOptions(el,selected=1){el.innerHTML=sems.map(s=>`<option value="${s}" ${s==selected?'selected':''}>Semester ${s}</option>`).join('')}
function renderStudent(){ $('#studentName').textContent=me.nama;$('#dNama').textContent=me.nama;$('#dNim').textContent=me.nim;$('#dProdi').textContent=me.prodi;$('#dProdi2').textContent=me.prodi;$('#dStatus').textContent=me.status;$('#dSem').textContent=me.semester;$('#dSemText').textContent=me.semester;['bNama','bNim'].forEach((id,i)=>$('#'+id).textContent=i?me.nim:me.nama);$('#bBirth').textContent=`${me.tempat_lahir}, ${new Date(me.tanggal_lahir+'T00:00:00').toLocaleDateString('id-ID',{day:'2-digit',month:'long',year:'numeric'})}`;$('#bGender').textContent=me.jenis_kelamin;$('#bProdi').textContent=me.prodi;$('#bFakultas').textContent=me.fakultas;$('#bSemester').textContent=me.semester;$('#bStatus').textContent=me.status;semOptions($('#krsSemester'),me.semester);semOptions($('#khsSemester'),me.semester);$('#krsProdi').textContent=me.prodi;$('#krsSemester').onchange=loadKrs;$('#khsSemester').onchange=loadKhs;loadDashboard()}
async function loadDashboard(){let d=await api('student_academic&semester='+me.semester).catch(()=>null);if(d){$('#dIP').textContent=Number(d.ip).toFixed(2);$('#dSKS').textContent=d.rows.reduce((a,r)=>a+Number(r.sks),0);}}
async function loadKrs(){let sem=Number($('#krsSemester').value);let [c,k]=await Promise.all([api(`courses&prodi=${encodeURIComponent(me.prodi)}&semester=${sem}`),api('krs')]);let rows=k.krs.filter(r=>Number(r.semester)===sem);let selected=new Set(rows.map(r=>r.kode));$('#courseSelect').innerHTML='<option value="">-- Pilih Mata Kuliah --</option>'+c.courses.filter(x=>!selected.has(x.kode)).map(x=>`<option value="${x.id}">${esc(x.kode)} - ${esc(x.nama)} (${x.sks} SKS)</option>`).join('');$('#krsTable').innerHTML=rows.length?rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.kode)}</td><td>${esc(r.nama)}</td><td>${r.sks}</td><td>${esc(r.status)}</td><td><button class="action-btn danger-link" onclick="removeKrs(${r.id})">Hapus</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">Belum ada KRS.</td></tr>';$('#totalSKS').textContent=rows.reduce((a,r)=>a+Number(r.sks),0)}
$('#addKrs').onclick=async()=>{try{await api('add_krs',{method:'POST',body:new URLSearchParams({semester:$('#krsSemester').value,course_id:$('#courseSelect').value})});loadKrs()}catch(e){alert(e.message)}};
async function removeKrs(id){if(confirm('Hapus mata kuliah ini dari KRS?')){await api('delete_krs',{method:'POST',body:new URLSearchParams({id})});loadKrs()}}
async function loadKhs(){let d=await api('student_academic&semester='+$('#khsSemester').value);$('#ipSemester').textContent=Number(d.ip).toFixed(2);$('#khsTable').innerHTML=d.rows.length?d.rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.kode)}</td><td>${esc(r.nama)}</td><td>${r.sks}</td><td>${esc(r.nilai||'-')}</td><td>${Number(r.bobot).toFixed(2)}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">Belum ada data nilai.</td></tr>'}
async function loadTranskrip(){let all=[];for(let s=1;s<=14;s++){let d=await api('student_academic&semester='+s);all.push(...d.rows.map(r=>({...r,semester:s})))}$('#transkripTable').innerHTML=all.filter(r=>r.nilai).map((r,i)=>`<tr><td>${i+1}</td><td>${r.semester}</td><td>${esc(r.kode)}</td><td>${esc(r.nama)}</td><td>${r.sks}</td><td>${esc(r.nilai)}</td><td>${Number(r.bobot).toFixed(2)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Belum ada nilai.</td></tr>';$('#dLulus').textContent=all.filter(r=>r.nilai&&Number(r.bobot)>=2).reduce((a,r)=>a+Number(r.sks),0)}
async function loadAdmin(){let d=await api('admin_students');students=d.students;let s=await api('admin_stats');$('#aTotal').textContent=s.stats.total;$('#aIf').textContent=s.stats.informatika;$('#aMesin').textContent=s.stats.mesin;$('#aLingkungan').textContent=s.stats.lingkungan;renderAdminStudents();populateStudentSelects();loadAdminCourses();loadAdminKrs();loadAdminGrades()}
function populateStudentSelects(){let html='<option value="">-- Pilih Mahasiswa --</option>'+students.map(s=>`<option value="${s.id}">${esc(s.nim)} - ${esc(s.nama)} (${esc(s.prodi)})</option>`).join('');$('#adminKrsStudent').innerHTML=html;$('#adminGradeStudent').innerHTML=html;$('#adminKrsStudent').onchange=loadAdminKrs;$('#adminKrsSem').onchange=loadAdminKrs;$('#adminGradeStudent').onchange=loadAdminGrades;$('#adminGradeSem').onchange=loadAdminGrades}
function renderAdminStudents(){let q=($('#studentSearch')?.value||'').toLowerCase();let a=students.filter(s=>(s.nama+s.nim+s.prodi).toLowerCase().includes(q));$('#adminStudentTable').innerHTML=a.map((s,i)=>`<tr><td>${i+1}</td><td><strong>${esc(s.nim)}</strong></td><td>${esc(s.nama)}<br><small>${esc(s.tempat_lahir)}, ${esc(s.tanggal_lahir)}</small></td><td>${esc(s.prodi)}</td><td><select class="status-select" onchange="updateStudent(${s.id},this.value,'semester')">${sems.map(x=>`<option value="${x}" ${x==s.semester?'selected':''}>${x}</option>`).join('')}</select></td><td><select class="status-select" onchange="updateStudent(${s.id},this.value,'status')">${['Aktif','Cuti','Nonaktif'].map(x=>`<option ${x===s.status?'selected':''}>${x}</option>`).join('')}</select></td><td>${new Date(s.created_at).toLocaleDateString('id-ID')}</td><td><button class="action-btn danger-link" onclick="deleteStudent(${s.id})">Hapus</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">Belum ada mahasiswa.</td></tr>'}
$('#studentSearch').oninput=renderAdminStudents;
async function updateStudent(id,val,field){let s=students.find(x=>x.id==id);let semester=field==='semester'?val:s.semester,status=field==='status'?val:s.status;await api('admin_update_student',{method:'POST',body:new URLSearchParams({id,semester,status})});loadAdmin()}
async function deleteStudent(id){if(confirm('Hapus mahasiswa dan seluruh data KRS/nilai terkait?')){await api('admin_delete_student',{method:'POST',body:new URLSearchParams({id})});loadAdmin()}}
$$('.admin-menu button').forEach(b=>b.onclick=()=>{$$('.admin-menu button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.admin-section').forEach(s=>s.classList.remove('active'));$('#'+b.dataset.adminSection).classList.add('active');$('#adminTitle').textContent=b.textContent.replace(/^\S+\s/,'')});
async function loadAdminCourses(){let d=await api(`courses&prodi=${encodeURIComponent($('#adminCourseProdi').value)}&semester=${$('#adminCourseSem').value}`);$('#adminCourseTable').innerHTML=d.courses.map((c,i)=>`<tr><td>${i+1}</td><td>${esc(c.kode)}</td><td>${esc(c.nama)}</td><td>${c.sks}</td></tr>`).join('')}
$('#adminCourseProdi').onchange=loadAdminCourses;$('#adminCourseSem').onchange=loadAdminCourses;
async function loadAdminKrs(){let sid=$('#adminKrsStudent').value;if(!sid){$('#adminKrsTable').innerHTML='<tr><td colspan="5" class="empty">Pilih mahasiswa.</td></tr>';return}let d=await api(`admin_krs&student_id=${sid}&semester=${$('#adminKrsSem').value}`);$('#adminKrsTable').innerHTML=d.rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.kode)}</td><td>${esc(r.nama)}</td><td>${r.sks}</td><td>${esc(r.status)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Belum ada KRS.</td></tr>'}
async function loadAdminGrades(){let sid=$('#adminGradeStudent').value;if(!sid){$('#adminGradeTable').innerHTML='<tr><td colspan="6" class="empty">Pilih mahasiswa.</td></tr>';return}let d=await api(`admin_krs&student_id=${sid}&semester=${$('#adminGradeSem').value}`);let opts=['A','AB','B','BC','C','CD','D','E'];$('#adminGradeTable').innerHTML=d.rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.kode)}</td><td>${esc(r.nama)}</td><td>${r.sks}</td><td><select class="grade-select" id="g${r.id}"><option value="">-</option>${opts.map(x=>`<option ${x===r.nilai?'selected':''}>${x}</option>`).join('')}</select></td><td><button class="action-btn" onclick="saveGrade(${r.id})">Simpan</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Belum ada KRS.</td></tr>'}
async function saveGrade(id){let v=$('#g'+id).value;if(!v)return alert('Pilih nilai terlebih dahulu.');await api('admin_grade',{method:'POST',body:new URLSearchParams({krs_id:id,nilai:v})});alert('Nilai berhasil disimpan.');loadAdminGrades()}
init();
