<?php
session_start();
require_once __DIR__.'/config.php';
$action=$_GET['api']??'';
if($action){
 try{
  if($action==='login' && $_SERVER['REQUEST_METHOD']==='POST'){
   $username=clean($_POST['username']);$password=(string)($_POST['password']??'');
   $st=db()->prepare("SELECT * FROM users WHERE username=? LIMIT 1");$st->execute([$username]);$u=$st->fetch();
   if(!$u||!password_verify($password,$u['password_hash'])) json_response(['ok'=>false,'message'=>'Username atau password salah.'],422);
   $_SESSION['user']=['id'=>(int)$u['id'],'username'=>$u['username'],'role'=>$u['role']];
   if($u['role']==='mahasiswa'){$st=db()->prepare('SELECT * FROM students WHERE user_id=?');$st->execute([$u['id']]);$_SESSION['student']=$st->fetch();}
   json_response(['ok'=>true,'role'=>$u['role']]);
  }
  if($action==='logout'){session_destroy();json_response(['ok'=>true]);}
  if($action==='register' && $_SERVER['REQUEST_METHOD']==='POST'){
   $d=$_POST;$req=['username','password','nim','nama','tempat_lahir','tanggal_lahir','jenis_kelamin','prodi','fakultas','semester','status'];foreach($req as $k)if(clean($d[$k])==='')json_response(['ok'=>false,'message'=>'Semua data wajib diisi.'],422);
   if(!in_array($d['prodi'],['Teknik Informatika','Teknik Mesin','Teknik Lingkungan'],true)||!in_array((int)$d['semester'],range(1,14),true))json_response(['ok'=>false,'message'=>'Program studi/semester tidak valid.'],422);
   $pdo=db();$pdo->beginTransaction();
   $st=$pdo->prepare('SELECT id FROM users WHERE username=?');$st->execute([clean($d['username'])]);if($st->fetch())throw new Exception('Username sudah digunakan.');
   $st=$pdo->prepare('SELECT id FROM students WHERE nim=?');$st->execute([clean($d['nim'])]);if($st->fetch())throw new Exception('NIM sudah terdaftar.');
   $st=$pdo->prepare('INSERT INTO users(username,password_hash,role) VALUES(?,?,\'mahasiswa\')');$st->execute([clean($d['username']),password_hash((string)$d['password'],PASSWORD_DEFAULT)]);$uid=$pdo->lastInsertId();
   $st=$pdo->prepare('INSERT INTO students(user_id,nim,nama,tempat_lahir,tanggal_lahir,jenis_kelamin,prodi,fakultas,semester,status) VALUES(?,?,?,?,?,?,?,?,?,?)');$st->execute([$uid,clean($d['nim']),clean($d['nama']),clean($d['tempat_lahir']),$d['tanggal_lahir'],$d['jenis_kelamin'],$d['prodi'],clean($d['fakultas']),$d['semester'],$d['status']]);
   $pdo->commit();json_response(['ok'=>true,'message'=>'Pendaftaran berhasil. Silakan login.']);
  }
  $u=require_login();$pdo=db();
  if($action==='me'){
   if($u['role']==='mahasiswa'){$st=$pdo->prepare('SELECT * FROM students WHERE user_id=?');$st->execute([$u['id']]);json_response(['ok'=>true,'user'=>$u,'student'=>$st->fetch()]);}
   json_response(['ok'=>true,'user'=>$u]);
  }
  if($action==='courses'){
   $prodi=clean($_GET['prodi']??'');$sem=(int)($_GET['semester']??1);$st=$pdo->prepare('SELECT * FROM courses WHERE prodi=? AND semester=? ORDER BY kode');$st->execute([$prodi,$sem]);json_response(['ok'=>true,'courses'=>$st->fetchAll()]);
  }
  if($action==='krs' && $u['role']==='mahasiswa'){
   $st=$pdo->prepare('SELECT k.id,c.kode,c.nama,c.sks,k.semester,k.status FROM krs k JOIN students s ON s.id=k.student_id JOIN courses c ON c.id=k.course_id WHERE s.user_id=? ORDER BY k.semester,c.kode');$st->execute([$u['id']]);json_response(['ok'=>true,'krs'=>$st->fetchAll()]);
  }
  if($action==='add_krs' && $u['role']==='mahasiswa'){
   $sem=(int)$_POST['semester'];$course=(int)$_POST['course_id'];$st=$pdo->prepare('SELECT s.id,c.sks FROM students s JOIN courses c ON c.prodi=s.prodi WHERE s.user_id=? AND c.id=? AND c.semester=?');$st->execute([$u['id'],$course,$sem]);$row=$st->fetch();if(!$row)json_response(['ok'=>false,'message'=>'Mata kuliah tidak valid.'],422);
   $st=$pdo->prepare('SELECT COALESCE(SUM(c.sks),0) total FROM krs k JOIN courses c ON c.id=k.course_id WHERE k.student_id=? AND k.semester=?');$st->execute([$row['id'],$sem]);if((int)$st->fetch()['total']+(int)$row['sks']>MAX_SKS)json_response(['ok'=>false,'message'=>'Maksimal KRS adalah 24 SKS.'],422);
   try{$pdo->prepare('INSERT INTO krs(student_id,course_id,semester) VALUES(?,?,?)')->execute([$row['id'],$course,$sem]);$pdo->prepare('INSERT INTO grades(krs_id,nilai,bobot) VALUES(LAST_INSERT_ID(),NULL,0)')->execute();json_response(['ok'=>true]);}catch(PDOException $e){json_response(['ok'=>false,'message'=>'Mata kuliah sudah ada di KRS.'],422);}
  }
  if($action==='delete_krs' && $u['role']==='mahasiswa'){$id=(int)$_POST['id'];$st=$pdo->prepare('DELETE k FROM krs k JOIN students s ON s.id=k.student_id WHERE k.id=? AND s.user_id=?');$st->execute([$id,$u['id']]);json_response(['ok'=>true]);}
  if($action==='student_academic' && $u['role']==='mahasiswa'){
   $sem=(int)($_GET['semester']??1);$st=$pdo->prepare('SELECT c.kode,c.nama,c.sks,g.nilai,g.bobot,k.semester,k.status FROM krs k JOIN students s ON s.id=k.student_id JOIN courses c ON c.id=k.course_id LEFT JOIN grades g ON g.krs_id=k.id WHERE s.user_id=? AND k.semester=? ORDER BY c.kode');$st->execute([$u['id'],$sem]);$rows=$st->fetchAll();$points=0;$sks=0;foreach($rows as $r){$sks+=(int)$r['sks'];$points+=(float)$r['sks']*(float)$r['bobot'];}$ip=$sks?round($points/$sks,2):0;json_response(['ok'=>true,'rows'=>$rows,'ip'=>$ip]);
  }
  if($action==='admin_students'){
   require_admin();$st=$pdo->query('SELECT s.*,u.username FROM students s JOIN users u ON u.id=s.user_id ORDER BY s.created_at DESC');json_response(['ok'=>true,'students'=>$st->fetchAll()]);
  }
  if($action==='admin_stats'){
   require_admin();$total=(int)$pdo->query('SELECT COUNT(*) n FROM students')->fetch()['n'];$out=['total'=>$total];foreach(['Teknik Informatika'=>'informatika','Teknik Mesin'=>'mesin','Teknik Lingkungan'=>'lingkungan'] as $p=>$k){$st=$pdo->prepare('SELECT COUNT(*) n FROM students WHERE prodi=?');$st->execute([$p]);$out[$k]=(int)$st->fetch()['n'];}json_response(['ok'=>true,'stats'=>$out]);
  }
  if($action==='admin_update_student'){
   require_admin();$id=(int)$_POST['id'];$semester=(int)$_POST['semester'];$status=clean($_POST['status']);if(!in_array($semester,range(1,14),true)||!in_array($status,['Aktif','Cuti','Nonaktif'],true))json_response(['ok'=>false,'message'=>'Data tidak valid.'],422);$pdo->prepare('UPDATE students SET semester=?,status=? WHERE id=?')->execute([$semester,$status,$id]);json_response(['ok'=>true]);
  }
  if($action==='admin_delete_student'){require_admin();$id=(int)$_POST['id'];$pdo->prepare('DELETE FROM students WHERE id=?')->execute([$id]);json_response(['ok'=>true]);}
  if($action==='admin_krs'){
   require_admin();$sid=(int)($_GET['student_id']??0);$sem=(int)($_GET['semester']??1);$st=$pdo->prepare('SELECT k.id,c.kode,c.nama,c.sks,g.nilai,g.bobot,k.status FROM krs k JOIN courses c ON c.id=k.course_id LEFT JOIN grades g ON g.krs_id=k.id WHERE k.student_id=? AND k.semester=? ORDER BY c.kode');$st->execute([$sid,$sem]);json_response(['ok'=>true,'rows'=>$st->fetchAll()]);
  }
  if($action==='admin_grade'){
   require_admin();$id=(int)$_POST['krs_id'];$nilai=clean($_POST['nilai']);$map=['A'=>4,'AB'=>3.5,'B'=>3,'BC'=>2.5,'C'=>2,'CD'=>1.5,'D'=>1,'E'=>0,'-'=>0];if(!array_key_exists($nilai,$map))json_response(['ok'=>false,'message'=>'Nilai tidak valid.'],422);$pdo->prepare('INSERT INTO grades(krs_id,nilai,bobot) VALUES(?,?,?) ON DUPLICATE KEY UPDATE nilai=VALUES(nilai),bobot=VALUES(bobot)')->execute([$id,$nilai,$map[$nilai]]);json_response(['ok'=>true]);
  }
  json_response(['ok'=>false,'message'=>'API tidak ditemukan.'],404);
 }catch(Throwable $e){if($pdo??null && $pdo->inTransaction())$pdo->rollBack();json_response(['ok'=>false,'message'=>$e->getMessage()],500);}
}
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=esc(APP_NAME)?> - <?=esc(INSTITUTION)?></title><link rel="stylesheet" href="style.css"></head><body>
<div id="loginPage" class="auth-page"><div class="auth-card auth-modern"><div class="brand-login"><img src="logo-itaf.png"><div><strong>SIAKAD ITAF</strong><span><?=esc(INSTITUTION)?></span></div></div><div class="auth-mode"><button id="studentMode" class="auth-mode-btn active">Mahasiswa</button><button id="adminMode" class="auth-mode-btn">Admin</button></div>
<form id="loginForm"><div class="form-group"><label>Username / NIM</label><input name="username" required></div><div class="form-group"><label>Password</label><input name="password" type="password" required></div><button class="btn btn-primary auth-submit">Masuk</button><p id="loginMsg" class="auth-message"></p></form>
<form id="registerForm" style="display:none"><div class="form-row"><div class="form-group"><label>Username</label><input name="username" required></div><div class="form-group"><label>Password</label><input name="password" type="password" minlength="6" required></div></div><div class="form-row"><div class="form-group"><label>NIM</label><input name="nim" required></div><div class="form-group"><label>Nama Lengkap</label><input name="nama" required></div></div><div class="form-row"><div class="form-group"><label>Tempat Lahir</label><input name="tempat_lahir" required></div><div class="form-group"><label>Tanggal Lahir</label><input name="tanggal_lahir" type="date" required></div></div><div class="form-row"><div class="form-group"><label>Jenis Kelamin</label><select name="jenis_kelamin"><option>Laki-laki</option><option>Perempuan</option></select></div><div class="form-group"><label>Status</label><select name="status"><option>Aktif</option><option>Cuti</option><option>Nonaktif</option></select></div></div><div class="form-row"><div class="form-group"><label>Program Studi</label><select name="prodi"><option>Teknik Informatika</option><option>Teknik Mesin</option><option>Teknik Lingkungan</option></select></div><div class="form-group"><label>Semester</label><select name="semester"><?php for($i=1;$i<=14;$i++):?><option value="<?=$i?>">Semester <?=$i?></option><?php endfor;?></select></div></div><div class="form-group"><label>Fakultas</label><input name="fakultas" value="Fakultas Teknologi" required></div><button class="btn btn-success auth-submit">Daftar Mahasiswa</button><p id="registerMsg" class="auth-message"></p></form><button id="registerToggle" class="auth-link">Belum punya akun? Daftar mahasiswa baru</button><div id="adminHint" class="demo-credential" style="display:none">Admin demo: <strong>admin</strong> / <strong>admin123</strong></div></div></div>
<div id="studentApp" class="app-content"><aside class="sidebar"><div class="logo"><img src="logo-itaf.png"><h2>SIAKAD ITAF</h2><p><?=esc(INSTITUTION)?></p></div><ul class="menu"><li><button class="active" data-section="dashboard">🏠 Dashboard</button></li><li><button data-section="biodata">👤 Biodata</button></li><li><button data-section="krs">📚 Pengisian KRS</button></li><li><button data-section="khs">📊 KHS</button></li><li><button data-section="transkrip">📄 Transkrip Nilai</button></li></ul><div class="sidebar-footer">© 2026 ITAF</div></aside><main class="main"><div class="topbar"><div><h1 id="pageTitle">Dashboard</h1><div class="institution"><?=esc(INSTITUTION)?></div></div><div class="topbar-right">Mahasiswa: <span id="studentName" class="student-name"></span><button id="studentLogout" class="btn btn-danger">Keluar</button></div></div>
<section id="dashboard" class="section active"><div class="cards"><div class="card"><h3>IP Semester</h3><div id="dIP" class="number">0.00</div></div><div class="card"><h3>SKS Semester</h3><div id="dSKS" class="number">0</div></div><div class="card"><h3>Total SKS Lulus</h3><div id="dLulus" class="number">0</div></div><div class="card"><h3>Semester Aktif</h3><div id="dSem" class="number">-</div></div></div><div class="panel"><h2>Informasi Akademik</h2><div class="notice"><strong>Program Studi:</strong> <span id="dProdi"></span> | <strong>Semester:</strong> <span id="dSemText"></span></div><div class="biodata"><div><strong>Nama</strong><span id="dNama"></span></div><div><strong>NIM</strong><span id="dNim"></span></div><div><strong>Program Studi</strong><span id="dProdi2"></span></div><div><strong>Status</strong><span id="dStatus"></span></div></div></div></section>
<section id="biodata" class="section"><div class="panel"><h2>Biodata Mahasiswa</h2><div class="biodata"><div><strong>Nama Lengkap</strong><span id="bNama"></span></div><div><strong>NIM</strong><span id="bNim"></span></div><div><strong>Tempat, Tanggal Lahir</strong><span id="bBirth"></span></div><div><strong>Jenis Kelamin</strong><span id="bGender"></span></div><div><strong>Program Studi</strong><span id="bProdi"></span></div><div><strong>Fakultas</strong><span id="bFakultas"></span></div><div><strong>Semester</strong><span id="bSemester"></span></div><div><strong>Status</strong><span id="bStatus"></span></div></div></div></section>
<section id="krs" class="section"><div class="panel"><h2>Pengisian Kartu Rencana Studi</h2><div class="toolbar"><div class="form-group compact"><label>Semester</label><select id="krsSemester"></select></div><div class="semester-badge">Prodi: <strong id="krsProdi"></strong></div></div><div class="krs-info"><div>Maksimal SKS: <strong>24</strong></div><div>Total Dipilih: <strong id="totalSKS">0</strong> SKS</div></div><div class="form-group"><label>Mata Kuliah</label><select id="courseSelect"></select></div><button id="addKrs" class="btn btn-primary">+ Tambah Mata Kuliah</button></div><div class="panel"><h2>Daftar KRS</h2><div class="table-container"><table><thead><tr><th>No</th><th>Kode</th><th>Mata Kuliah</th><th>SKS</th><th>Status</th><th>Aksi</th></tr></thead><tbody id="krsTable"></tbody></table></div></div></section>
<section id="khs" class="section"><div class="panel"><h2>Kartu Hasil Studi</h2><div class="form-group semester-select"><label>Semester</label><select id="khsSemester"></select></div><div class="ip-box"><h3>Indeks Prestasi Semester</h3><div id="ipSemester" class="ip-value">0.00</div></div><div class="table-container"><table><thead><tr><th>No</th><th>Kode</th><th>Mata Kuliah</th><th>SKS</th><th>Nilai</th><th>Bobot</th></tr></thead><tbody id="khsTable"></tbody></table></div></div></section>
<section id="transkrip" class="section"><div class="panel"><h2>Transkrip Nilai</h2><div class="table-container"><table><thead><tr><th>No</th><th>Semester</th><th>Kode</th><th>Mata Kuliah</th><th>SKS</th><th>Nilai</th><th>Bobot</th></tr></thead><tbody id="transkripTable"></tbody></table></div></div></section></main></div>
<div id="adminApp" class="admin-content"><aside class="admin-sidebar"><div class="admin-brand"><img src="logo-itaf.png"><strong>ADMIN SIAKAD</strong><span>INSTITUT TEKNOLOGI ALBERTH FOENAY</span></div><ul class="admin-menu"><li><button class="active" data-admin-section="adminDashboard">🏠 Dashboard</button></li><li><button data-admin-section="adminStudents">👥 Data Mahasiswa</button></li><li><button data-admin-section="adminCourses">📚 Mata Kuliah</button></li><li><button data-admin-section="adminKrs">📝 Monitoring KRS</button></li><li><button data-admin-section="adminGrades">📊 Input Nilai</button></li></ul></aside><main class="admin-main"><div class="admin-topbar"><div><h1 id="adminTitle">Dashboard Admin</h1><div class="institution"><?=esc(INSTITUTION)?></div></div><div><span class="admin-badge">ADMIN</span> <button id="adminLogout" class="btn btn-danger">Keluar</button></div></div>
<section id="adminDashboard" class="admin-section active"><div class="admin-hero"><div><span class="eyebrow">SISTEM INFORMASI AKADEMIK</span><h2>Selamat Datang, Administrator</h2><p>Kelola data mahasiswa, mata kuliah, KRS, dan nilai secara terpusat melalui database MySQL.</p></div><img src="logo-itaf.png"></div><div class="admin-stat-grid"><div class="admin-stat"><span>👥</span><div><small>Total Mahasiswa</small><strong id="aTotal">0</strong></div></div><div class="admin-stat"><span>💻</span><div><small>Teknik Informatika</small><strong id="aIf">0</strong></div></div><div class="admin-stat"><span>⚙️</span><div><small>Teknik Mesin</small><strong id="aMesin">0</strong></div></div><div class="admin-stat"><span>🌿</span><div><small>Teknik Lingkungan</small><strong id="aLingkungan">0</strong></div></div></div><div class="admin-panel"><h3>Integrasi Database</h3><p>Setiap pendaftaran mahasiswa tersimpan di MySQL dan langsung tersedia di Portal Admin, termasuk dari perangkat yang berbeda jika server online.</p></div></section>
<section id="adminStudents" class="admin-section"><div class="admin-panel"><div class="panel-heading"><div><h2>Data Mahasiswa</h2><p>Semua mahasiswa yang terdaftar di database.</p></div><input id="studentSearch" placeholder="Cari nama / NIM..."></div><div class="table-container"><table class="admin-table"><thead><tr><th>No</th><th>NIM</th><th>Nama</th><th>Prodi</th><th>Semester</th><th>Status</th><th>Daftar</th><th>Aksi</th></tr></thead><tbody id="adminStudentTable"></tbody></table></div></div></section>
<section id="adminCourses" class="admin-section"><div class="admin-panel"><h2>Katalog Mata Kuliah</h2><div class="admin-filters"><select id="adminCourseProdi"><option>Teknik Informatika</option><option>Teknik Mesin</option><option>Teknik Lingkungan</option></select><select id="adminCourseSem"><?php for($i=1;$i<=14;$i++):?><option value="<?=$i?>">Semester <?=$i?></option><?php endfor;?></select></div><div class="table-container"><table class="admin-table"><thead><tr><th>No</th><th>Kode</th><th>Mata Kuliah</th><th>SKS</th></tr></thead><tbody id="adminCourseTable"></tbody></table></div></div></section>
<section id="adminKrs" class="admin-section"><div class="admin-panel"><h2>Monitoring KRS</h2><div class="admin-filters"><select id="adminKrsStudent"></select><select id="adminKrsSem"><?php for($i=1;$i<=14;$i++):?><option value="<?=$i?>">Semester <?=$i?></option><?php endfor;?></select></div><div class="table-container"><table class="admin-table"><thead><tr><th>No</th><th>Kode</th><th>Mata Kuliah</th><th>SKS</th><th>Status</th></tr></thead><tbody id="adminKrsTable"></tbody></table></div></div></section>
<section id="adminGrades" class="admin-section"><div class="admin-panel"><h2>Input Nilai Mahasiswa</h2><div class="admin-filters"><select id="adminGradeStudent"></select><select id="adminGradeSem"><?php for($i=1;$i<=14;$i++):?><option value="<?=$i?>">Semester <?=$i?></option><?php endfor;?></select></div><div class="table-container"><table class="admin-table"><thead><tr><th>No</th><th>Kode</th><th>Mata Kuliah</th><th>SKS</th><th>Nilai</th><th>Simpan</th></tr></thead><tbody id="adminGradeTable"></tbody></table></div></div></section>
</main></div><script src="app.js"></script></body></html>
